INSERT INTO categories(name)
VALUES('Camera & Photo'),
      ('Headphones'),
      ('Speakers'),
      ('Fax Machines'),
      ('Printers'),
      ('Scanners'),
      ('Video Game Consoles & Accessories'),
      ('Video Projectors'),
      ('Desktop Computers'),
      ('Laptops'),
      ('Tablets'),
      ('External Solid State Drives'),
      ('Cell Phones & Accessories'),
      ('Monitors'),
      ('Others');
